# ── Build stage ─────────────────────────────────────────────
# Multi-stage build: compile Go binary in golang image, run in alpine
#
# Build context: project root (docker build -f Dockerfile .)
# Go source code lives in app/
#
# NOTE: On node-01 (no Docker Hub access), build with daocloud mirror URLs:
#   docker.m.daocloud.io/library/golang:1.22-alpine
#   docker.m.daocloud.io/library/alpine:3.20
# The build-push.sh script handles this substitution automatically.
FROM golang:1.22-alpine AS builder

WORKDIR /build

# Cache dependencies (go.sum is generated by go mod download)
# GOPROXY=goproxy.cn: Chinese Go module proxy (fast, no VPN needed)
COPY app/go.mod ./
ENV GOPROXY=https://goproxy.cn
RUN go mod download

# Copy source, generate go.sum, and build static binary
COPY app/ .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o shortlink .

# ── Runtime stage ───────────────────────────────────────────
# alpine provides ca-certificates (needed for HTTPS redirects) + tzdata
FROM alpine:3.20

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app
COPY --from=builder /build/shortlink .

EXPOSE 8080

# Non-root user for security
RUN adduser -D -u 10001 appuser
USER appuser

CMD ["./shortlink"]
