---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
  labels:
    app.kubernetes.io/part-of: backup-system
  annotations:
    velero.io/timezone: Asia/Shanghai
spec:
  schedule: "30 2 * * *"
  template:
    includedNamespaces:
      - data-layer
      - app-layer
    defaultVolumesToFsBackup: true
    ttl: 168h0m0s
    storageLocation: default
